//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Areas.CustomerManagement.Pages {
    
    
    public partial class CreateCustomerAccount {
        
        /// <summary>
        /// NoChannelPermissionsRecordError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoChannelPermissionsRecordError;
        
        /// <summary>
        /// ChannelPermissionsError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet ChannelPermissionsError;
        
        /// <summary>
        /// NoParentAccountError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoParentAccountError;
        
        /// <summary>
        /// NoChannelPermissionsForParentAccountError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoChannelPermissionsForParentAccountError;
        
        /// <summary>
        /// ParentAccountClassificationCodeError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet ParentAccountClassificationCodeError;
        
        /// <summary>
        /// CreateAccountForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel CreateAccountForm;
        
        /// <summary>
        /// WebFormDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.CrmDataSource WebFormDataSource;
        
        /// <summary>
        /// AccountFormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.CrmEntityFormView AccountFormView;
        
        /// <summary>
        /// CreateAccountButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CreateAccountButton;
    }
}
