//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Areas.CustomerManagement.Pages {
    
    
    public partial class EditCustomerAccount {
        
        /// <summary>
        /// RecordNotFoundError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet RecordNotFoundError;
        
        /// <summary>
        /// NoChannelPermissionsRecordError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoChannelPermissionsRecordError;
        
        /// <summary>
        /// ChannelPermissionsError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet ChannelPermissionsError;
        
        /// <summary>
        /// NoParentAccountError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoParentAccountError;
        
        /// <summary>
        /// NoChannelPermissionsForParentAccountError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoChannelPermissionsForParentAccountError;
        
        /// <summary>
        /// ParentAccountClassificationCodeError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet ParentAccountClassificationCodeError;
        
        /// <summary>
        /// SuccessMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet SuccessMessage;
        
        /// <summary>
        /// EditAccountForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel EditAccountForm;
        
        /// <summary>
        /// AccountForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel AccountForm;
        
        /// <summary>
        /// FormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.CrmEntityFormView FormView;
        
        /// <summary>
        /// NoContactsExistWarningMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.Snippet NoContactsExistWarningMessage;
        
        /// <summary>
        /// PrimaryContactLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PrimaryContactLabel;
        
        /// <summary>
        /// PrimaryContactList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList PrimaryContactList;
        
        /// <summary>
        /// UpdateAccountButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button UpdateAccountButton;
        
        /// <summary>
        /// ContactsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ContactsList;
        
        /// <summary>
        /// CreateContactButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adxstudio.Xrm.Web.UI.WebControls.SiteMarkerLinkButton CreateContactButton;
        
        /// <summary>
        /// AccountContactsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView AccountContactsList;
    }
}
